name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache pytest cache
        uses: actions/cache@v4
        with:
          path: .pytest_cache
          key: ${{ runner.os }}-pytest-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-pytest-
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Byte-compile
        run: python -m compileall .
      - name: Lint & formatting checks (ruff)
        run: |
          pip install ruff
          # Fail the job if code is not formatted or lint rules fail
          ruff format --check .
          ruff check .
      - name: Run all Django tests
        working-directory: django_app
        env:
          DJANGO_SETTINGS_MODULE: ai_framework.test_settings
        run: |
          python manage.py test
      - name: Run top-level pytest (src/tests)
        env:
          DJANGO_SETTINGS_MODULE: ai_framework.test_settings
        run: |
          pip install pytest pytest-django
          # Use pytest-django's --ds flag to point to the Django test settings
          python -m pytest -q --ds=ai_framework.test_settings
